#!/bin/bash -l
# lightest possible entrypoint that ensures that
# we use a login shell to get a fully configured shell environment
# (e.g. sourcing /etc/profile.d, ~/.bashrc, and friends)
if [[ ! -z "${R2D_ENTRYPOINT:-}" ]]; then
    usermod -g users annika
    exec "$R2D_ENTRYPOINT" "$@"
else
    usernod -g users annika
    exec "$@"
fi
